// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDqyXJHKIulHGuiuL91MIaXeMiQt2PDms',
    appId: '1:190314785671:web:9572875fab63e265780122',
    messagingSenderId: '190314785671',
    projectId: 'listify-67d3d',
    authDomain: 'listify-67d3d.firebaseapp.com',
    storageBucket: 'listify-67d3d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDALbLN1PGMZMF477DzF2FPA40zpX_V8Mw',
    appId: '1:190314785671:android:504cce9b17123b3d780122',
    messagingSenderId: '190314785671',
    projectId: 'listify-67d3d',
    storageBucket: 'listify-67d3d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK6QrsPnPZLQJR4yKd0bXoM8cxQfFQVz4',
    appId: '1:190314785671:ios:e7585fab9027850f780122',
    messagingSenderId: '190314785671',
    projectId: 'listify-67d3d',
    storageBucket: 'listify-67d3d.appspot.com',
    iosClientId: '190314785671-8jd7a9d7pj1cd65c6bp2eq0s8h67geqe.apps.googleusercontent.com',
    iosBundleId: 'com.example.listify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCK6QrsPnPZLQJR4yKd0bXoM8cxQfFQVz4',
    appId: '1:190314785671:ios:e7585fab9027850f780122',
    messagingSenderId: '190314785671',
    projectId: 'listify-67d3d',
    storageBucket: 'listify-67d3d.appspot.com',
    iosClientId: '190314785671-8jd7a9d7pj1cd65c6bp2eq0s8h67geqe.apps.googleusercontent.com',
    iosBundleId: 'com.example.listify',
  );
}
